auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Lu, boyan from V2EX
url: http://luboyan-hub.github.io
feed: /atom.xml
author_info: <a href="http://luboyan-hub.github.io/">Lu, boyan</a>

myblog:
  gavatar: e58263391ae73db1f891203074a3c6c2
  gpname: luboyan-hub
  linkedin: https://www.linkedin.com/in/%E7%81%8F-%E5%91%A8-9018a3163
  github: https://github.com/luboyan-hub
  coverimgs: []
  postbgimg: https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=4198197184,1084779842&fm=27&gp=0.jpg

prose:
  rooturl: "_posts"
  # siteurl: "http://liyu1981.github.io/"
  media: "images"
  metadata:
    _posts/blog:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          placeholder: "Input your title here"
          type: "text"

      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
          placeholder: "Input your abstract here"
          type: "text"

      - name: "layout"
        field:
          element: "hidden"
          value: "post"

      - name: "published"
        field:
          element: "hidden"
          value: "true"

      - name: "category"
        field:
          element: "hidden"
          value: "blog"
